### ISSUE TITLE
The layout is constantly refreshing with onHover event

### ISSUE THREAD

**Issue by FRYoussef** [plotly/dash-cytoscape#42] opened 2019-03-19 19:09 UTC
#### Description

Hi,
I've found a bug related with the layout, when the graph has been loaded if you put the mouse over any node, the graph's layout will start to move, it seems like the layout is constantly refreshing with onHover event. It happens in dash-cytoscape==0.0.5 and 0.0.4 but not in 0.0.3 version.

#### Steps/Code to Reproduce

I've tried to make an example but i couldn't reproduce it, but you can check it in this [page.](http://staging.networks.wikichron.science/app/?network=user_talk_network&wikis=cocktails.wikia.com&upper_bound=1546767583&lower_bound=1116495583)
Click the link and when the graph is loaded try to put the mouse over a node.

#### Expected Results

A static layout.

#### Actual Results

No error in the console log, but constantly layout initialization.

#### Versions

We are using 0.0.5 version.

**Comment by xhlulu** [comment] 2019-03-19 23:51
This error definitely seems pretty odd. It's hard to reproduce this since it's embedded in an entire Dash system. I would suggest you to turn off `autoRefreshLayout` (please take a look at the references). Maybe check in the callbacks to see if you are updating the layout anywhere where you aren't expecting to do so?

Let me know if you are able to isolate the problem!

**Comment by FRYoussef** [comment] 2019-03-22 14:18
Well, I've gotten to isolated the bug, as you say it's pretty odd, let's see the code:

```python3
import dash
import dash_cytoscape as cyto
import dash_html_components as html
from dash.dependencies import Input, Output, State
import pickle
from dash.exceptions import PreventUpdate

app = dash.Dash(__name__)

with open('cyto_graph2.bin', 'rb') as handle:
    cy_net = pickle.load(handle)
    
app.layout = html.Div([
    cyto.Cytoscape(
        id='cytoscape',
        elements = cy_net['network'],
        maxZoom = 1.75,
        minZoom = 0.35,
        layout = {
            'name': 'cose',
            'idealEdgeLength': 100,
            'nodeOverlap': 20,
            'refresh': 20,
            'fit': True,
            'padding': 30,
            'randomize': False,
            'componentSpacing': 100,
            'nodeRepulsion': 400000,
            'edgeElasticity': 100,
            'nestingFactor': 5,
            'gravity': 80,
            'numIter': 1000,
            'initialTemp': 200,
            'coolingFactor': 0.95,
            'minTemp': 1.0
        },
        style = {
            'height': '65vh',
            'width': 'calc(100% - 300px)'
        },
        stylesheet = [{
                'selector': 'node',
                'style': {
                    'content': '',
                    'text-halign': 'center',
                    'text-valign': 'top',
                    'text-background-color': '#FFFFFF',
                    'text-background-opacity': '1',
                    'font-size': '12',
                    'background-color': '#78909C',
                    'height': f"mapData(num_edits, {cy_net['min_node_size']}, {cy_net['max_node_size']}, 10, 60)",
                    'width': f"mapData(num_edits, {cy_net['min_node_size']}, {cy_net['max_node_size']}, 10, 60)"
                }
            },
            {
                'selector': 'edge',
                'style': {
                    'width': f"mapData(weight, {cy_net['min_edge_size']}, \
			            {cy_net['max_edge_size']}, 1, 30)",
                    'opacity': '1',
                    'line-color': '#000000',
                    'curve-style': 'bezier',
                    'target-arrow-shape': 'triangle',
                    'target-arrow-color': '#3E2723'
                }
            }]
    )
])

@app.callback(
    Output('cytoscape', 'elements'),
    [Input('cytoscape', 'tapNodeData')]
)
def click(data):
    print(data)
    raise PreventUpdate()


if __name__ == '__main__':
    app.run_server(debug=True)
```

If you comment the callback section, the layout won't refresh. 
In addition, the calbacks's print is never called, so I think it's an event error previous to the dash callback.
Use the file which follows to test the code.  
[cyto_graph2.zip](https://github.com/plotly/dash-cytoscape/files/2996851/cyto_graph2.zip)

**Comment by xhlulu** [comment] 2019-03-22 14:51
Thanks for isolating the problem! Could I ask why you would like to raise a PreventUpdate?

**Comment by xhlulu** [comment] 2019-03-22 14:54
I'll try out your example today and get back soon!

**Comment by FRYoussef** [comment] 2019-03-22 15:38
> 
> 
> Thanks for isolating the problem! Could I ask why you would like to raise a PreventUpdate?

Ooh, that's because I was trying to check if the callback was launched, but it wasn't, you can replace it for None if you want.

**Comment by xhlulu** [comment] 2019-03-22 20:50
Hmm after investigating the problem, I think the fastest fix is to set `autoRefreshLayout` to false, i.e.
```python
cyto.Cytoscape(
  id='cytoscape',
  autoRefreshLayout=False,
  elements=[...],
  ...
)
```

Furthermore, I tried replacing your elements with the following elements:
```python
basic_elements = [
    {
        'data': {'id': 'one', 'label': 'Node 1'},
        'position': {'x': 50, 'y': 50}
    },
    {
        'data': {'id': 'two', 'label': 'Node 2'},
        'position': {'x': 200, 'y': 200}
    },
    {
        'data': {'id': 'three', 'label': 'Node 3'},
        'position': {'x': 100, 'y': 150}
    },
    {
        'data': {'id': 'four', 'label': 'Node 4'},
        'position': {'x': 400, 'y': 50}
    },
    {
        'data': {'id': 'five', 'label': 'Node 5'},
        'position': {'x': 250, 'y': 100}
    },
    {
        'data': {'id': 'six', 'label': 'Node 6', 'parent': 'three'},
        'position': {'x': 150, 'y': 150}
    },
    {
        'data': {
            'source': 'one',
            'target': 'two',
            'label': 'Edge from Node1 to Node2'
        }
    },
    {
        'data': {
            'source': 'one',
            'target': 'five',
            'label': 'Edge from Node 1 to Node 5'
        }
    },
    {
        'data': {
            'source': 'two',
            'target': 'four',
            'label': 'Edge from Node 2 to Node 4'
        }
    },
    {
        'data': {
            'source': 'three',
            'target': 'five',
            'label': 'Edge from Node 3 to Node 5'
        }
    },
    {
        'data': {
            'source': 'three',
            'target': 'two',
            'label': 'Edge from Node 3 to Node 2'
        }
    },
    {'data': {
        'source': 'four',
        'target': 'four',
        'label': 'Edge from Node 4 to Node 4'
    }
    },
    {
        'data': {
            'source': 'four',
            'target': 'six',
            'label': 'Edge from Node 4 to Node 6'
        }
    },
    {
        'data': {
            'source': 'five',
            'target': 'one',
            'label': 'Edge from Node 5 to Node 1'
        }
    },
]
```
and the problem seems to have gone away. I've also commented out the parts of the stylesheet where you are using 'min_edge_size' and 'max_edge_size', but I don't think these are the cause of the problem.

Since you stored your dictionary with pickle it is impossible for me to see how you defined it. Have you tried looking into how you declared your elements (before storing them in a pickle file), maybe that could give you some hints?

**Comment by FRYoussef** [comment] 2019-03-23 13:25
Finally, I've found the error, I think if you set such a big integer for id, it'll broke XD, so I've used a string instead of a python integer.
This is the dictionary I used.
```python3
[
    {'data': {'id': 0, 'label': 0}}, 
    {'data': {'id': 108559, 'label': 1}}, 
    {'data': {'id': 130807, 'label': 2}}, 
    {'data': {'id': 20290, 'label': 3}}, 
    {'data': {'id': 901205, 'label': 4}}, 
    {'data': {'id': 256722, 'label': 5}}, 
    {'data': {'id': 1735815, 'label': 6}},
    {'data': {'id': 390665, 'label': 7}}, 
    {'data': {'id': 2101021, 'label': 8}}, 
    {'data': {'id': 3263655, 'label': 9}}, 
    {'data': {'id': 20251, 'label': 10}}, 
    {'data': {'id': 3100864, 'label': 11}}, 
    {'data': {'id': 3351845, 'label': 12}}, 
    {'data': {'id': 3513322, 'label': 13}}, 
    {'data': {'id': 3002955, 'label': 14}}, 
    {'data': {'id': 136752, 'label': 15}}, 
    {'data': {'id': 1984019, 'label': 16}}, 
    {'data': {'id': 4148139, 'label': 17}}, 
    {'data': {'id': 1416077, 'label': 18}}, 
    {'data': {'id': 5659711, 'label': 19}}, 
    {'data': {'id': 4968017, 'label': 20}}, 
    {'data': {'id': 7689575, 'label': 21}}, 
    {'data': {'id': 7699233, 'label': 22}}, 
    {'data': {'id': 6773618, 'label': 23}}, 
    {'data': {'id': 20644,'label': 24}}, 
    {'data': {'id': 188432, 'label': 25}}, 
    {'data': {'id': 7699234, 'label': 26}}, 
    {'data': {'id': 7699236, 'label': 27}}, 
    {'data': {'id': 7699238, 'label': 28}},
    {'data': {'id': 7699240, 'label': 29}},
    {'data': {'id': 7699242, 'label': 30}},
    {'data': {'id': 7699243, 'label': 31}},
    {'data': {'id': 7699244, 'label': 32}},
    {'data': {'id': 7699245, 'label': 33}},
    {'data': {'id': 7699246, 'label': 34}},
    {'data': {'id': 7699247, 'label': 35}},
    {'data': {'id': 7699248, 'label': 36}},
    {'data': {'id': 7699249, 'label': 37}},
    {'data': {'id': 7699250, 'label': 38}},
    {'data': {'id': 7699251, 'label': 39}},
    {'data': {'id': 7699252, 'label': 40}},
    {'data': {'id': 7699253, 'label': 41}},
    {'data': {'id': 7699254, 'label': 42}},
    {'data': {'id': 7699255, 'label': 43}},
    {'data': {'id': 7699256, 'label': 44}},
    {'data': {'id': 7699257, 'label': 45}},
    {'data': {'id': 7699258, 'label': 46}},
    {'data': {'id': 7699259, 'label': 47}},
    {'data': {'id': 7699260, 'label': 48}},
    {'data': {'id': 7699261, 'label': 49}},
    {'data': {'id': 7699262, 'label': 50}},
    {'data': {'id': 7699263, 'label': 51}},
    {'data': {'id': 7699264, 'label': 52}},
    {'data': {'id': 7699265, 'label': 53}},
    {'data': {'id': 7699266, 'label': 54}},
    {'data': {'id': 7699267, 'label': 55}},
    {'data': {'id': 7699268, 'label': 56}},
    {'data': {'id': 7699269, 'label': 57}},
    {'data': {'id': 7699270, 'label': 58}},
    {'data': {'id': 7699271, 'label': 59}},
    {'data': {'id': 7699272, 'label': 60}},
    {'data': {'id': 7699273, 'label': 61}},
    {'data': {'id': 7699274, 'label': 62}},
    {'data': {'id': 7699275, 'label': 63}},
    {'data': {'id': 7699276, 'label': 64}},
    {'data': {'id': 108560, 'source': 0, 'target': 108559}},
    {'data': {'id': 7699235, 'source': 0, 'target': 7699234}},
    {'data': {'id': 7699237, 'source': 0, 'target': 7699236}},
    {'data': {'id': 7699239, 'source': 0, 'target': 7699238}},
    {'data': {'id': 7699241, 'source': 0, 'target': 7699240}},
    {'data': {'id': 466257354706754, 'source': 108559, 'target': 20290}},
    {'data': {'id': 561811787108162, 'source': 130807, 'target': 20290}},
    {'data': {'id': 3870646002011970, 'source': 901205, 'target': 20290}},
    {'data': {'id': 1102612594184002, 'source': 256722, 'target': 20290}},
    {'data': {'id': 7455268656926530, 'source': 1735815, 'target': 20290}},
    {'data': {'id': 17816121344282434, 'source': 4148139, 'target': 20290}},
    {'data': {'id': 6082004403638082, 'source': 1416077, 'target': 20290}},
    {'data': {'id': 87144886566647, 'source': 20290, 'target': 130807}},
    {'data': {'id': 87144894135082, 'source': 20290, 'target': 7699242}},
    {'data': {'id': 87144894135083, 'source': 20290, 'target': 7699243}},
    {'data': {'id': 87144894135084, 'source': 20290, 'target': 7699244}},
    {'data': {'id': 87144887337045, 'source': 20290, 'target': 901205}},
    {'data': {'id': 87144894135085, 'source': 20290, 'target': 7699245}},
    {'data': {'id': 87144894135086, 'source': 20290, 'target': 7699246}},
    {'data': {'id': 87144894135087, 'source': 20290, 'target': 7699247}},
    {'data': {'id': 87144894135088, 'source': 20290, 'target': 7699248}},
    {'data': {'id': 87144894135089, 'source': 20290, 'target': 7699249}},
    {'data': {'id': 87144886692562, 'source': 20290, 'target': 256722}},
    {'data': {'id': 1677893406391090, 'source': 390665, 'target': 7699250}},
    {'data': {'id': 9023816490908467, 'source': 2101021, 'target': 7699251}},
    {'data': {'id': 7455268664605492, 'source': 1735815, 'target': 7699252}},
    {'data': {'id': 7455268664605493, 'source': 1735815, 'target': 7699253}},
    {'data': {'id': 7455268664605494, 'source': 1735815, 'target': 7699254}},
    {'data': {'id': 7455268664605495, 'source': 1735815, 'target': 7699255}},
    {'data': {'id': 14017291490817545, 'source': 3263655, 'target': 390665}},
    {'data': {'id': 86977390410552, 'source': 20251, 'target': 7699256}},
    {'data': {'id': 13318109477043001, 'source': 3100864, 'target': 7699257}},
    {'data': {'id': 13318109477043002, 'source': 3100864, 'target': 7699258}},
    {'data': {'id': 13318109477043003, 'source': 3100864, 'target': 7699259}},
    {'data': {'id': 13318109477043004, 'source': 3100864, 'target': 7699260}},
    {'data': {'id': 13318109477043005, 'source': 3100864, 'target': 7699261}},
    {'data': {'id': 13318109477043006, 'source': 3100864, 'target': 7699262}},
    {'data': {'id': 13318109477043007, 'source': 3100864, 'target': 7699263}},
    {'data': {'id': 13318109477043008, 'source': 3100864, 'target': 7699264}},
    {'data': {'id': 13318109477043009, 'source': 3100864, 'target': 7699265}},
    {'data': {'id': 1677893406391106, 'source': 390665, 'target': 7699266}},
    {'data': {'id': 13318109477043011, 'source': 3100864, 'target': 7699267}},
    {'data': {'id': 13318109477043012, 'source': 3100864, 'target': 7699268}},
    {'data': {'id': 13318109477043013, 'source': 3100864, 'target': 7699269}},
    {'data': {'id': 15089603093418176, 'source': 3513322, 'target': 3100864}},
    {'data': {'id': 587345370763456, 'source': 136752, 'target': 3100864}},
    {'data': {'id': 13318109472857066, 'source': 3100864, 'target': 3513322}},
    {'data': {'id': 13318109477043014, 'source': 3100864, 'target': 7699270}},
    {'data': {'id': 13318109477043015, 'source': 3100864, 'target': 7699271}},
    {'data': {'id': 13318109477043016, 'source': 3100864, 'target': 7699272}},
    {'data': {'id': 12897593524058953, 'source': 3002955, 'target': 7699273}},
    {'data': {'id': 6082004409277503, 'source': 1416077, 'target': 5659711}},
    {'data': {'id': 21337470542388109, 'source': 4968017, 'target': 1416077}},
    {'data': {'id': 33026473146555277, 'source': 7689575, 'target': 1416077}},
    {'data': {'id': 24308273651227533, 'source': 5659711, 'target': 1416077}},
    {'data': {'id': 33067953940700045, 'source': 7699233, 'target': 1416077}},
    {'data': {'id': 29092467787013005, 'source': 6773618, 'target': 1416077}},
    {'data': {'id': 88665306274701, 'source': 20644, 'target': 1416077}},
    {'data': {'id': 809309278935949, 'source': 188432, 'target': 1416077}},
    {'data': {'id': 13318109477043018, 'source': 3100864, 'target': 7699274}},
    {'data': {'id': 6082004411317067, 'source': 1416077, 'target': 7699275}},
    {'data': {'id': 13318109477043020, 'source': 3100864, 'target': 7699276}},
    {'data': {'id': 88665309826641, 'source': 20644, 'target': 4968017}}
]
```

**Comment by xhlulu** [comment] 2019-03-23 13:39
That would make sense! It is rather weird that using a large integer would cause this kind of problems... I think it might be caused by Python reassigning the id values every time you hover over an element, which causes the elements to be updated, thus triggering the layout to be automatically ran again.

Since it's an edge case, and using strings instead of integer solves it, I guess it is fair to close this for now. However, anyone is encouraged to reopen this if the issue rises again in other situations. 

We will likely add a note in the Cytoscape docs to make sure this confusion doesn't arise in the future.

**Closed by xhlulu** 2019-03-23 13:39 UTC
